# Generated by Django 3.2 on 2021-07-09 16:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210709_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('I', 'Income'), ('O', 'Outcome')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motivation',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 19, 24, 36, 747349)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 19, 24, 36, 763339)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='from_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 9, 19, 24, 36, 748348)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 9, 19, 24, 36, 763339)),
        ),
    ]
