# Generated by Django 3.2 on 2021-08-10 17:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210709_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='backend.employee'),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='motivation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivations', to='backend.employee'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='backend.subscription'),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='backend.employee'),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratios', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='backend.client'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='from_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 10, 20, 13, 31, 447351)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='backend.project'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 10, 20, 13, 31, 447351)),
        ),
        migrations.AlterUniqueTogether(
            name='ratio',
            unique_together={('employee', 'project')},
        ),
    ]
