# Generated by Django 3.2 on 2021-08-11 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210810_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratio',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ratios', to='backend.space'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='from_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 11, 22, 31, 39, 958300)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 11, 22, 31, 39, 958300)),
        ),
    ]
