# Generated by Django 3.2 on 2021-08-11 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210811_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='from_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 11, 23, 10, 47, 533432)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 11, 23, 10, 47, 533432)),
        ),
        migrations.AlterUniqueTogether(
            name='ratio',
            unique_together=set(),
        ),
    ]
